### ISSUE TITLE
Issue with the depedency

### ISSUE THREAD

**Issue by mdebony** [AndresTanasijczuk/SlurmDagman#2]
Hello,
I've installed the software using pip. I then use it submit DAG but all the jobs are submitted at the same time without caring at all for the dependency.
As example I've made this very simple DAG and all the job were submitted at the same time and run at the same time. So the job B wasn't waiting for A to finish before starting.
`JOB A a.sh

JOB B b.sh

PARENT A CHILD B`

How could I avoid this issue ?

Thanks in advance for the answer,
Best,

**Comment by AndresTanasijczuk** [comment]
Hi Mathieu,
Can you attach your .slurm_dagman.out file please?

**Comment by AndresTanasijczuk** [comment]
I confirm this issue happens in python 3. I will fix it.

Also the slurm_cancel_dag command had a python3 incompatibility bug, which I fixed yesterday.

**Comment by AndresTanasijczuk** [comment]
SlurmDagman 0.1.5 should now be fully compatible with python 3, fixing this issue in particular.

**Comment by mdebony** [comment]
Hi,
Sorry for this late answering, I didn't get the notification from github.
Thanks a lot for solving the issue.
